plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
}

android {
    signingConfigs {
        release {
            storeFile file('../signing.jks')
            storePassword 'toanthai'
            keyAlias 'signing'
            keyPassword 'toanthai'
        }
    }

    namespace 'io.edenx.androidplayground'
    compileSdk 33

    defaultConfig {
        applicationId "io.edenx.androidpark"
        minSdk 24
        targetSdk 33
        versionCode 7
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            manifestPlaceholders = [appName: "Andrd Playgrnd"]
            buildConfigField "String", "APP_NAME", "\"Andrd Playgrnd\""
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            manifestPlaceholders = [appName: "Andrd Playgrnd"]
            buildConfigField "String", "APP_NAME", "\"Andrd Playgrnd\""
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation libs.bundles.androidx.base
    implementation libs.bundles.lifecycle
    implementation libs.androidx.lifecycle.process

    implementation libs.hilt.android
    ksp libs.hilt.compiler

    implementation platform(libs.firebase.bom)
    implementation libs.bundles.firebase

    implementation libs.play.services.ads
    implementation libs.play.services.wallet
    implementation libs.play.app.update.ktx
    implementation libs.billing.ktx

    implementation libs.bundles.camerax
    implementation libs.bundles.mlkit
    implementation libs.zxing.core

    implementation libs.bundles.media3
    implementation libs.androidx.paging.runtime
    implementation libs.bundles.navigation

    implementation libs.bundles.retrofit
    implementation libs.kotlinx.coroutines.android
    implementation libs.glide

    testImplementation libs.junit4
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
